apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-staging-cert
  namespace: staging
spec:
  secretName: wildcard-staging-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.euno-staging.reactiflux.com"
