# Apply with: kubectl apply -f cluster/cluster-issuer.yaml
# This configures cert-manager to issue TLS certificates via Let's Encrypt.
# HTTP-01 is used for regular certs, DNS-01 for wildcard certs.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vcarl@reactiflux.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      # Default: HTTP-01 for regular certificates
      - http01:
          ingress:
            class: nginx
      # DNS-01 for wildcard certificates (staging previews)
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns-token
              key: access-token
        selector:
          dnsNames:
            - "*.euno-staging.reactiflux.com"
