#!/usr/bin/env bash
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

if echo "$changed_files" | grep -q "^package-lock.json$"; then
  echo "📦 Dependencies changed. Running npm install..."
  npm install
fi
