#!/usr/bin/env sh
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo "❌ Direct commits to main are not allowed. Please use a feature branch."
  exit 1
fi

npx lint-staged
