# Gateway Service (Discord.js gateway connections)
# Each pod connects to Discord and handles a subset of guilds

apiVersion: v1
kind: Service
metadata:
  name: gateway-internal
  labels:
    app: mod-bot
    component: gateway
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: mod-bot
    component: gateway

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gateway
  labels:
    app: mod-bot
    component: gateway
spec:
  serviceName: gateway-internal
  replicas: 3  # Start with 3 pods, scale manually
  selector:
    matchLabels:
      app: mod-bot
      component: gateway
  template:
    metadata:
      labels:
        app: mod-bot
        component: gateway
    spec:
      containers:
        - name: gateway
          image: $(IMAGE)
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: SERVICE_MODE
              value: "gateway"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: CONFIG_SERVICE_URL
              value: "http://config-service:3001"
            - name: DATABASE_URL
              value: "/data/mod-bot.sqlite3"
          envFrom:
            - secretRef:
                name: modbot-env
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
        
        # Litestream sidecar for continuous backup to S3
        - name: litestream
          image: litestream/litestream:0.3
          args:
            - "replicate"
          env:
            - name: LITESTREAM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: LITESTREAM_ACCESS_KEY_ID
            - name: LITESTREAM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: LITESTREAM_SECRET_ACCESS_KEY
          volumeMounts:
            - name: data
              mountPath: /data
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      
      volumes:
        - name: litestream-config
          configMap:
            name: litestream-config
  
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage

---
# Litestream configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: litestream-config
  labels:
    app: mod-bot
    component: gateway
data:
  litestream.yml: |
    dbs:
      - path: /data/mod-bot.sqlite3
        replicas:
          - type: s3
            bucket: ${LITESTREAM_BUCKET}
            path: gateway-${POD_ORDINAL}
            endpoint: ${LITESTREAM_ENDPOINT}
            region: ${LITESTREAM_REGION}
            force-path-style: true
