# HTTP Service Deployment (Web portal and webhook handler)

apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    app: mod-bot
    component: http
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: mod-bot
    component: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-service
  labels:
    app: mod-bot
    component: http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mod-bot
      component: http
  template:
    metadata:
      labels:
        app: mod-bot
        component: http
    spec:
      containers:
        - name: http-service
          image: $(IMAGE)
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: SERVICE_MODE
              value: "http"
            - name: CONFIG_SERVICE_URL
              value: "http://config-service:3001"
            - name: GATEWAY_SERVICE_URL
              value: "http://gateway-internal:3000"
          envFrom:
            - secretRef:
                name: modbot-env
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2

---
# Horizontal Pod Autoscaler for HTTP service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-service-hpa
  labels:
    app: mod-bot
    component: http
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
