name: CD
concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: Euno-HQ/hosting/.github/workflows/docker-build.yml@main

  deploy:
    needs: build
    uses: Euno-HQ/hosting/.github/workflows/deploy.yml@main
    with:
      app_name: mod-bot
      statefulset_name: mod-bot-set
      secret_name: modbot-env
      staging_secret_name: modbot-staging-env
    secrets:
      DIGITAL_OCEAN_K8S: ${{ secrets.DIGITAL_OCEAN_K8S }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      EMERGENCY_WEBHOOK: ${{ secrets.EMERGENCY_WEBHOOK }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
      DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
      DISCORD_HASH: ${{ secrets.DISCORD_HASH }}
      DISCORD_TEST_GUILD: ${{ secrets.DISCORD_TEST_GUILD }}
      SENTRY_INGEST: ${{ secrets.SENTRY_INGEST }}
      SENTRY_RELEASES: ${{ secrets.SENTRY_RELEASES }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      VITE_PUBLIC_POSTHOG_KEY: ${{ secrets.VITE_PUBLIC_POSTHOG_KEY }}
      VITE_PUBLIC_POSTHOG_HOST: ${{ secrets.VITE_PUBLIC_POSTHOG_HOST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
