name: Preview Cleanup

on:
  pull_request:
    types: [closed, labeled]

env:
  HUSKY: 0

jobs:
  cleanup:
    uses: Euno-HQ/hosting/.github/workflows/preview-cleanup.yml@main
    with:
      app_name: mod-bot
    secrets:
      DIGITAL_OCEAN_K8S: ${{ secrets.DIGITAL_OCEAN_K8S }}
